#!/usr/bin/env bash

# This script transfers a file to a remote server's home directory using scp.

# Check if 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Use scp to transfer the file to the user's home directory (~) on the remote server
# -o StrictHostKeyChecking=no disables the strict host key check
# -i specifies the identity file (SSH key)
# The destination is formatted as USERNAME@IP:~/
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
